RELATIVE = 1;
ALTR_LIN = 2;
ALTR_POLY = 3;
RANDOM = 4;
FIXED = 5;
RANKSVM = 6;
ALTR_RBF_KER = 7;
ALTR_LIN_CHUNKING = 8;
ALTR_POLY_KER_CHUNKING = 9;
ALTR_MULTI = 10;
RANKSVM_WEIGHTED = 11;
ALTR_LIN_WEIGHTED = 12;
RANKSVM_WEIGHTED_BAD = 13;
REGRESSION = 14;
ALTR_LIN_DUAL = 15;
ALTR_LIN_NO_WEAK = 16;

epsilon =  0.0000001;